repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: mixed-line-ending

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        files: \.(css|js|md|yml|yaml)$
        args: ["--prose-wrap=preserve"]

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.2
    hooks:
      - id: djlint-reformat
        files: \.(html)$
        args: ["--indent=2"]
      - id: djlint
        files: \.(html)$
        args: ["--ignore=H006,H013,H021,H023,H030,H031"]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.31.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
